---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml 

  roles:
    - role: geerlingguy.mysql 
      tags: [ local ]


- hosts: all
  become: yes
  gather_facts: true

  vars_files:
    - vars/main.yml 
  roles:
    - role: community.zabbix.zabbix_server
     
- hosts: all
  become: yes
  gather_facts: true
  vars_files:
    - vars/main.yml 
  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: community.zabbix.zabbix_web